CREATE TRIGGER DelUserReview AFTER DELETE ON userFOR EACH ROW DELETE FROM review WHERE uid = OLD.uid;

CREATE TRIGGER DelUserRental AFTER DELETE ON user FOR EACH ROW DELETE FROM rental WHERE uid = OLD.uid;